name: takeaway_app_flutter_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  slang: ^3.30.0
  slang_flutter: ^3.30.0
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.2.0
  badges: ^3.1.2
  url_launcher: ^6.2.5
  app_links: ^6.4.0
  flutter_svg: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  web_socket_channel: ^2.4.0
  intl: ^0.18.1
  timezone: ^0.10.1
  step_progress_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  slang_build_runner: ^3.30.0
  build_runner: ^2.4.9 

flutter:
  uses-material-design: true
  assets:
    - assets/images/IDEAL.svg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon_min.png"