name: takeaway_app_flutter_client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  slang: ^3.30.0
  slang_flutter: ^3.30.0
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  slang_build_runner: ^3.30.0
  build_runner: ^2.4.9 

flutter:
  uses-material-design: true
  assets:
    - assets/.env.dev